name: Revalidate a cada 2 horas

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  revalidate:
    runs-on: ubuntu-latest
    steps:
      - name: Revalidar página inicial
        run: |
          curl -L -H "x-revalidate-secret: ${{ secrets.REVALIDATION_SECRET }}" "${{ secrets.SITE_URL }}/api/revalidate"
